/**
 * Key for "CORRECT" results, denoted by 🟩
 *
 * @type {"correct"}
 */
export const CORRECT_KEY = "correct";
/**
 * Key for "MISTAKE" results, denoted by 🟨
 *
 * @type {"mistake"}
 */
export const MISTAKE_KEY = "mistake";
/**
 * Key for "HINT" results, denoted by 🟡
 *
 * @type {"hint"}
 */
export const HINT_KEY = "hint";
/**
 * Key for "DOUBLE HINT" results, denoted by 🟠
 *
 * @type {"doubleHint"}
 */
export const DOUBLE_HINT_KEY = "doubleHint";

/**
 * Dictionary to map the icon (generated by cluesbysam) to the key (used internally)
 *
 * @type {{ "🟩": string; "🟨": string; "🟡": string; "🟠": string; }}
 */
export const iconMap = {
  "🟩": CORRECT_KEY,
  ":large_green_square:": CORRECT_KEY,
  "🟨": MISTAKE_KEY,
  ":large_yellow_square:": MISTAKE_KEY,
  "🟡": HINT_KEY,
  ":large_yellow_circle:": HINT_KEY,
  "🟠": DOUBLE_HINT_KEY,
  ":large_orange_circle:": DOUBLE_HINT_KEY,
};

// Define standard patterns for emoji categories
export const CORRECT_REGEX = /🟩|:large_green_square:/;
export const MISTAKE_REGEX = /🟨|:large_yellow_square:/;
export const HINT_REGEX = /🟡|:large_yellow_circle:/;
export const DOUBLE_HINT_REGEX = /🟠|:large_orange_circle:/;
