/**
 * Key for "CORRECT" results, denoted by 🟩
 *
 * @type {"correct"}
 */
export const CORRECT_KEY = "correct";
/**
 * Key for "MISTAKE" results, denoted by 🟨
 *
 * @type {"mistake"}
 */
export const MISTAKE_KEY = "mistake";
/**
 * Key for "HINT" results, denoted by 🟡
 *
 * @type {"hint"}
 */
export const HINT_KEY = "hint";
/**
 * Key for "DOUBLE HINT" results, denoted by 🟠
 *
 * @type {"doubleHint"}
 */
export const DOUBLE_HINT_KEY = "doubleHint";

/**
 * Dictionary to map the icon (generated by cluesbysam) to the key (used internally)
 *
 * @type {{ "🟩": string; "🟨": string; "🟡": string; "🟠": string; }}
 */
export const iconMap = {
  "🟩": CORRECT_KEY,
  "🟨": MISTAKE_KEY,
  "🟡": HINT_KEY,
  "🟠": DOUBLE_HINT_KEY,
};
